name: PVPManager
version: 1.0.0
api: [5.0.0]
main: Cryotap\PVPManager\Main
author: Cryotap
description: PvP Admin Commands plugin for managing PvP features.

commands:
  pvpm:
    description: PvP Management
    usage: /pvpm editor
    permission: pvpmanager.logger

permissions:
  pvpmanager.logger:
    default: op
    description: Allows access to PvP admin commands.
  pvpmanager.editor:
    default: op
    description: Allows access to PvP admin commands.